[tool.poetry]
name = "pythonproject9"
version = "0.1.0"
description = ""
authors = ["Василиса Андросова <and3vasya@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
